# Generated by Django 5.1 on 2024-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='species/', verbose_name='Фото'),
        ),
    ]
