# Generated by Django 5.1 on 2024-08-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_specie_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'Антилокация', 'verbose_name_plural': 'Антилокации'},
        ),
        migrations.RemoveField(
            model_name='specie',
            name='photo',
        ),
        migrations.CreateModel(
            name='SpeciePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='species/', verbose_name='Фото')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'verbose_name': 'Фотография антилокации',
                'verbose_name_plural': 'Фотографии антилокации',
            },
        ),
    ]
